"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CharacterData = void 0;
exports.CharacterData = {
    player: {
        id: 1,
        name: 'Link',
        hp: 60,
        mp: 0,
        str: 15,
        int: 0,
        def: 0,
        res: 0,
        spd: 0,
        luck: 0,
        rarity: 0,
        class: 1,
        race: 1,
    },
    enemy: {
        id: 12,
        name: 'Bokoblin',
        hp: 30,
        mp: 0,
        str: 5,
        int: 0,
        def: 0,
        res: 0,
        spd: 0,
        luck: 0,
        rarity: 0,
        class: 2,
        race: 12,
    },
    boss: {
        id: 1,
        name: 'Ganon',
        hp: 150,
        mp: 0,
        str: 20,
        int: 0,
        def: 0,
        res: 0,
        spd: 0,
        luck: 0,
        rarity: 0,
        class: 8,
        race: 12,
    },
};
